### PR TITLE
Update to 0.11.0 release

### PR DESCRIPTION
**Pull request by brianv0**
There is  a 0.11.0 release of log4cxx available. 

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by brianv0** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Thanks!
It looks like some patches need to be removed?

Are you interested in being a co-maintainer? Feel free to add yourself in that case.

**Comment by brianv0** [comment]
`configure` wasn't working out of the box anymore and it seemed like they updated the CMakeLists, so I switched to cmake and dropped the patches and included `CMakeLists.txt`. cmake doesn't build the static library by default though, and I think I need to patch things in order to do so.

**Comment by wolfv** [comment]
that's good, we don't need and shouldn't have static libraries by default.

**Comment by wolfv** [comment]
since we're building the tests, could we also run them? `make test` or something like that?

**Comment by brianv0** [comment]
Well most the tests are working after some patches. I can't reproduce the errors in `timebasedrollingtest` on osx, so I'm not sure what's going on there - I didn't mangle my homebrew though.

I could patch that test out or I could skip tests on os x.

**Comment by wolfv** [comment]
both options are fine with me. Awesome stuff!

**Comment by brianv0** [comment]
working now - it's stuck waiting to get scheduled on drone.io for arm.

**Comment by brianv0** [comment]
@conda-forge-admin, please rerender

**Comment by brianv0** [comment]
I think this is ready for merge now

**Pull request merged**
