### PR TITLE
[WIP] Enable Windows build.

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
Some fixes need to be addressed first at [`apr-feedstock`](https://github.com/conda-forge/apr-feedstock/pull/6).

**Comment by wolfv** [comment]
looks good to me! only thing i am wondering if it would be more future-proof if we do something like `src/main/cpp/*.cpp` in the CMake so that no files are accidentally forgotten? (if that works).

**Comment by wolfv** [comment]
btw also feel free to add yourself as a maintainer if you want

**Comment by seanyen** [comment]
> looks good to me! only thing i am wondering if it would be more future-proof if we do something like `src/main/cpp/*.cpp` in the CMake so that no files are accidentally forgotten? (if that works).

Good idea! I changed to use the following way to collect the `.cpp` files:

```cmake
file(GLOB_RECURSE LOG4CXX_SRC
  "${PROJECT_SOURCE_DIR}/src/main/cpp/*.cpp"
)
```

**Comment by wolfv** [comment]
Do we need to wait for the apr package or should I merge?

**Comment by wolfv** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
apr was merged, so let's see if this builds fine for windows! :tada:

**Comment by wolfv** [comment]
I've merged as it was green. I hope you're ok with that :)

**Comment by seanyen** [comment]
> I've merged as it was green. I hope you're ok with that :)

No problem at all. Thanks for the release!

**Pull request merged**
